# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site_Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Data_Digital',
            fields=[
                ('data_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.Data_Base')),
            ],
            bases=('crawler.data_base',),
        ),
        migrations.CreateModel(
            name='Data_SeongSu',
            fields=[
                ('data_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.Data_Base')),
            ],
            bases=('crawler.data_base',),
        ),
        migrations.AddField(
            model_name='data_base',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.Site_Name'),
        ),
    ]
