# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-08 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_site_name_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Hyunime',
            fields=[
                ('data_base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crawler.Data_Base')),
            ],
            bases=('crawler.data_base',),
        ),
        migrations.AlterField(
            model_name='site_name',
            name='users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
